project:
  type: website
  output-dir: docs

website:
  title: "PeterWebsite"
  repo-url: https://github.com/phoward42/phoward42-practice
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: research.qmd
        text: My Research
    right: 
      - href: about.qmd
        icon: question
      - href: "https://github.com/phoward42/phoward42-practice"
        icon: github
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



